CREATE DATABASE IF NOT EXISTS tam_bebeong
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE tam_bebeong;

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL DEFAULT 'Administrator',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS respondents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  gender ENUM('Laki-laki', 'Perempuan') NOT NULL,
  age INT NOT NULL,
  work_unit VARCHAR(150) NOT NULL,
  position_name VARCHAR(120) NULL,
  education VARCHAR(50) NOT NULL,
  years_of_service INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS questionnaires (
  id INT AUTO_INCREMENT PRIMARY KEY,
  respondent_id INT NOT NULL,
  PEOU1 TINYINT NOT NULL,
  PEOU2 TINYINT NOT NULL,
  PEOU3 TINYINT NOT NULL,
  PEOU4 TINYINT NOT NULL,
  PEOU5 TINYINT NOT NULL,
  PEOU6 TINYINT NOT NULL,
  PEOU7 TINYINT NOT NULL,
  PU1 TINYINT NOT NULL,
  PU2 TINYINT NOT NULL,
  PU3 TINYINT NOT NULL,
  PU4 TINYINT NOT NULL,
  PU5 TINYINT NOT NULL,
  PU6 TINYINT NOT NULL,
  PU7 TINYINT NOT NULL,
  BI1 TINYINT NOT NULL,
  BI2 TINYINT NOT NULL,
  BI3 TINYINT NOT NULL,
  BI4 TINYINT NOT NULL,
  BI5 TINYINT NOT NULL,
  BI6 TINYINT NOT NULL,
  suggestion TEXT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_questionnaires_respondents
    FOREIGN KEY (respondent_id) REFERENCES respondents(id)
    ON DELETE CASCADE,
  CONSTRAINT chk_peou1 CHECK (PEOU1 BETWEEN 1 AND 5),
  CONSTRAINT chk_peou2 CHECK (PEOU2 BETWEEN 1 AND 5),
  CONSTRAINT chk_peou3 CHECK (PEOU3 BETWEEN 1 AND 5),
  CONSTRAINT chk_peou4 CHECK (PEOU4 BETWEEN 1 AND 5),
  CONSTRAINT chk_peou5 CHECK (PEOU5 BETWEEN 1 AND 5),
  CONSTRAINT chk_peou6 CHECK (PEOU6 BETWEEN 1 AND 5),
  CONSTRAINT chk_peou7 CHECK (PEOU7 BETWEEN 1 AND 5),
  CONSTRAINT chk_pu1 CHECK (PU1 BETWEEN 1 AND 5),
  CONSTRAINT chk_pu2 CHECK (PU2 BETWEEN 1 AND 5),
  CONSTRAINT chk_pu3 CHECK (PU3 BETWEEN 1 AND 5),
  CONSTRAINT chk_pu4 CHECK (PU4 BETWEEN 1 AND 5),
  CONSTRAINT chk_pu5 CHECK (PU5 BETWEEN 1 AND 5),
  CONSTRAINT chk_pu6 CHECK (PU6 BETWEEN 1 AND 5),
  CONSTRAINT chk_pu7 CHECK (PU7 BETWEEN 1 AND 5),
  CONSTRAINT chk_bi1 CHECK (BI1 BETWEEN 1 AND 5),
  CONSTRAINT chk_bi2 CHECK (BI2 BETWEEN 1 AND 5),
  CONSTRAINT chk_bi3 CHECK (BI3 BETWEEN 1 AND 5),
  CONSTRAINT chk_bi4 CHECK (BI4 BETWEEN 1 AND 5),
  CONSTRAINT chk_bi5 CHECK (BI5 BETWEEN 1 AND 5),
  CONSTRAINT chk_bi6 CHECK (BI6 BETWEEN 1 AND 5)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS jamovi_uploads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description TEXT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(100) NOT NULL,
  file_content LONGBLOB NOT NULL,
  uploaded_by INT NULL,
  uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_jamovi_uploads_admins
    FOREIGN KEY (uploaded_by) REFERENCES admins(id)
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE OR REPLACE VIEW v_questionnaire_scores AS
SELECT
  q.id,
  q.respondent_id,
  r.gender,
  r.work_unit,
  r.position_name,
  q.suggestion,
  q.submitted_at,
  ROUND((PEOU1 + PEOU2 + PEOU3 + PEOU4 + PEOU5 + PEOU6 + PEOU7) / 7, 2) AS peou_avg,
  ROUND((PU1 + PU2 + PU3 + PU4 + PU5 + PU6 + PU7) / 7, 2) AS pu_avg,
  ROUND((BI1 + BI2 + BI3 + BI4 + BI5 + BI6) / 6, 2) AS bi_avg
FROM questionnaires q
JOIN respondents r ON r.id = q.respondent_id;
